name: Build Obfuscate my_tro

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 1 * *"  # 每月1号 00:00 运行
  workflow_dispatch:     # 支持手动运行

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: Install dependencies
        run: |
          npm install -g javascript-obfuscator
          sudo apt-get install -y unzip

      - name: Download and extract latest my_tro worker
        run: |
          wget https://raw.githubusercontent.com/camel52zhang/my_tro/refs/heads/main/_worker.js
          mv _worker.js origin.js

      - name: Clean existing obfuscated files  # 新增清理步骤
        run: |
          rm -f _worker.js*

      - name: Obfuscate my_tro worker js
        run: |
          javascript-obfuscator origin.js --output _worker.js \
          --compact true \
          --identifier-names-generator hexadecimal \
          --rename-globals true \
          --string-array true \
          --string-array-encoding 'base64' \
          --string-array-threshold 0.75 \
          --transform-object-keys true \
          --self-defending false \
          --simplify true

      - name: 提交更改
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: ':arrow_up: update latest my_tro'
          commit_author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
          push_options: '--set-upstream'
